/** Copies the generated migrations into a module the runtime can import.
 *
 * `drizzle-kit generate` writes SQL files and a journal to disk, and reading
 * them back at boot is exactly what a Worker cannot do: a D1 deployment has a
 * database binding and a bundle, no filesystem. So the journal's contents are
 * inlined here instead, once, at generate time — the bundle carries the same
 * statements a local file applies, and there is no second code path to keep
 * honest.
 *
 * Runs as the second half of `bun run db:generate`; the output is committed.
 */
import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { Effect, Schema } from "effect"

const packageRoot = path.resolve(import.meta.dirname, "..")
const migrationsDirectory = path.join(packageRoot, "db", "migrations")
const outputPath = path.join(packageRoot, "src", "store-migrations.gen.ts")

/** The slice of drizzle-kit's journal this script depends on. `idx` orders the
 *  migrations and `tag` names the file; the rest is drizzle-kit's business. */
const Journal = Schema.Struct({
  entries: Schema.Array(Schema.Struct({
    idx: Schema.Int,
    tag: Schema.String
  }))
})

const decodeJournal = Schema.decodeUnknownSync(Journal)

/** drizzle-kit separates statements with a marker rather than a bare `;`,
 *  because a `;` inside a string literal or a trigger body is not a boundary. */
const statementBreakpoint = "--> statement-breakpoint"

const statementsOf = (tag: string): ReadonlyArray<string> =>
  readFileSync(path.join(migrationsDirectory, `${tag}.sql`), "utf8")
    .split(statementBreakpoint)
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0)

const render = (migrations: ReadonlyArray<{ readonly id: number; readonly name: string }>): string => {
  const entries = migrations.map((migration) => {
    // JSON, not a template literal: drizzle quotes identifiers with backticks.
    const statements = statementsOf(migration.name)
      .map((statement) => `      ${JSON.stringify(statement)}`)
      .join(",\n")
    return `  {
    id: ${migration.id},
    name: ${JSON.stringify(migration.name)},
    statements: [
${statements}
    ]
  }`
  }).join(",\n")

  return `// GENERATED by \`bun run db:generate\`. Do not edit.
//
// One entry per file in db/migrations, in journal order, split on drizzle's
// statement breakpoints. Applied by src/migrate.ts.

export interface GatewayMigration {
  /** Journal index. Stamped in \`gateway_migration\`, so it never shifts. */
  readonly id: number
  readonly name: string
  readonly statements: ReadonlyArray<string>
}

export const gatewayMigrations: ReadonlyArray<GatewayMigration> = [
${entries}
]
`
}

const program = Effect.sync(() => {
  const journal = decodeJournal(
    JSON.parse(readFileSync(path.join(migrationsDirectory, "meta", "_journal.json"), "utf8"))
  )
  const migrations = [...journal.entries]
    .sort((left, right) => left.idx - right.idx)
    .map((entry) => ({ id: entry.idx, name: entry.tag }))
  writeFileSync(outputPath, render(migrations))
  return migrations
}).pipe(
  Effect.tap((migrations) =>
    Effect.log(`embedded ${migrations.length} migration(s) into ${path.relative(packageRoot, outputPath)}`)
  )
)

await Effect.runPromise(program)
