import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { Effect, Schema } from "effect"

const packageRoot = path.resolve(import.meta.dirname, "..")
const migrationsDirectory = path.join(packageRoot, "db", "migrations")
const outputPath = path.join(packageRoot, "src", "store-migrations.gen.ts")

const Journal = Schema.Struct({
  entries: Schema.Array(Schema.Struct({
    idx: Schema.Int,
    tag: Schema.String
  }))
})

const decodeJournal = Schema.decodeUnknownSync(Journal)

const statementBreakpoint = "--> statement-breakpoint"

const statementsOf = (tag: string): ReadonlyArray<string> =>
  readFileSync(path.join(migrationsDirectory, `${tag}.sql`), "utf8")
    .split(statementBreakpoint)
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0)

const render = (migrations: ReadonlyArray<{ readonly id: number; readonly name: string }>): string => {
  const entries = migrations.map((migration) => {
    const statements = statementsOf(migration.name)
      .map((statement) => `      ${JSON.stringify(statement)}`)
      .join(",\n")
    return `  {
    id: ${migration.id},
    name: ${JSON.stringify(migration.name)},
    statements: [
${statements}
    ]
  }`
  }).join(",\n")

  return `// GENERATED by \`bun run db:generate\`. Do not edit.
//
// One entry per file in db/migrations, in journal order, split on drizzle's
// statement breakpoints. Applied by src/migrate.ts.

export interface GatewayMigration {
  /** Journal index. Stamped in \`gateway_migration\`, so it never shifts. */
  readonly id: number
  readonly name: string
  readonly statements: ReadonlyArray<string>
}

export const gatewayMigrations: ReadonlyArray<GatewayMigration> = [
${entries}
]
`
}

const program = Effect.sync(() => {
  const journal = decodeJournal(
    JSON.parse(readFileSync(path.join(migrationsDirectory, "meta", "_journal.json"), "utf8"))
  )
  const migrations = [...journal.entries]
    .sort((left, right) => left.idx - right.idx)
    .map((entry) => ({ id: entry.idx, name: entry.tag }))
  writeFileSync(outputPath, render(migrations))
  return migrations
}).pipe(
  Effect.tap((migrations) =>
    Effect.log(`embedded ${migrations.length} migration(s) into ${path.relative(packageRoot, outputPath)}`)
  )
)

await Effect.runPromise(program)
