// GENERATED by `bun run db:generate`. Do not edit.
//
// One entry per file in db/migrations, in journal order, split on drizzle's
// statement breakpoints.

import type { Migration } from "./migrate.ts"

export const integrationMigrations: ReadonlyArray<Migration> = [
  {
    id: 0,
    name: "0000_integrations_baseline",
    statements: [
      "CREATE TABLE `connection` (\n\t`owner` text NOT NULL,\n\t`integration` text NOT NULL,\n\t`name` text NOT NULL,\n\t`template` text NOT NULL,\n\t`provider` text NOT NULL,\n\t`identity_label` text,\n\t`description` text,\n\t`oauth_client` text,\n\t`oauth_client_owner` text,\n\t`oauth_scope` text,\n\t`expires_at` integer,\n\t`created_at` integer NOT NULL,\n\tPRIMARY KEY(`owner`, `integration`, `name`),\n\tFOREIGN KEY (`integration`) REFERENCES `integration`(`slug`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `connection_by_integration` ON `connection` (`integration`,`owner`);",
      "CREATE TABLE `credential` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`sealed` text NOT NULL\n);",
      "CREATE TABLE `integration` (\n\t`slug` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`kind` text NOT NULL,\n\t`endpoint` text,\n\t`spec_source` text,\n\t`spec_format` text,\n\t`base_url` text,\n\t`display_url` text,\n\t`auth_methods` text DEFAULT '[]' NOT NULL,\n\t`created_at` integer NOT NULL\n);",
      "CREATE TABLE `oauth_client` (\n\t`owner` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`integration` text NOT NULL,\n\t`client_id` text NOT NULL,\n\t`authorization_url` text NOT NULL,\n\t`token_url` text NOT NULL,\n\t`registration_endpoint` text,\n\t`issuer` text,\n\t`resource` text,\n\t`scopes` text DEFAULT '[]' NOT NULL,\n\t`token_auth_methods` text DEFAULT '[]' NOT NULL,\n\t`created_at` integer NOT NULL,\n\tPRIMARY KEY(`owner`, `slug`)\n);",
      "CREATE TABLE `oauth_flow` (\n\t`state` text PRIMARY KEY NOT NULL,\n\t`owner` text NOT NULL,\n\t`integration` text NOT NULL,\n\t`connection` text NOT NULL,\n\t`template` text NOT NULL,\n\t`client_owner` text NOT NULL,\n\t`client_slug` text NOT NULL,\n\t`code_verifier` text NOT NULL,\n\t`redirect_uri` text NOT NULL,\n\t`resource` text,\n\t`scopes` text DEFAULT '[]' NOT NULL,\n\t`created_at` integer NOT NULL\n);",
      "CREATE TABLE `spec_document` (\n\t`source` text PRIMARY KEY NOT NULL,\n\t`content` text NOT NULL,\n\t`fetched_at` integer NOT NULL\n);",
      "CREATE TABLE `tool` (\n\t`address` text PRIMARY KEY NOT NULL,\n\t`owner` text NOT NULL,\n\t`integration` text NOT NULL,\n\t`connection` text NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`read_only` integer DEFAULT 0 NOT NULL,\n\t`input_schema` text,\n\t`output_schema` text,\n\t`call` text NOT NULL,\n\t`captured_at` integer NOT NULL\n);",
      "CREATE INDEX `tool_by_connection` ON `tool` (`integration`,`owner`,`connection`);"
    ]
  },
  {
    id: 1,
    name: "0001_stiff_thor_girl",
    statements: [
      "ALTER TABLE `integration` ADD `mcp_era` text;"
    ]
  },
  {
    id: 2,
    name: "0002_stale_warstar",
    statements: [
      "CREATE TABLE `blob` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`content_type` text NOT NULL,\n\t`filename` text,\n\t`bytes` integer NOT NULL,\n\t`created_at` integer NOT NULL\n);",
      "CREATE TABLE `blob_chunk` (\n\t`blob` text NOT NULL,\n\t`seq` integer NOT NULL,\n\t`data` blob NOT NULL,\n\tPRIMARY KEY(`blob`, `seq`)\n);"
    ]
  }
]
