import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { Effect, Schema } from "effect"
import { Command, Flag } from "effect/unstable/cli"
import * as BunServices from "@effect/platform-bun/BunServices"

const Journal = Schema.Struct({
  entries: Schema.Array(Schema.Struct({ idx: Schema.Int, tag: Schema.String }))
})
const decodeJournal = Schema.decodeUnknownSync(Schema.fromJsonString(Journal))

const statementBreakpoint = "--> statement-breakpoint"

const render = (input: {
  readonly migrationsDirectory: string
  readonly exportName: string
  readonly typeImport: string
  readonly migrations: ReadonlyArray<{ readonly id: number; readonly name: string }>
}): string => {
  const entries = input.migrations.map((migration) => {
    const statements = readFileSync(path.join(input.migrationsDirectory, `${migration.name}.sql`), "utf8")
      .split(statementBreakpoint)
      .map((statement) => statement.trim())
      .filter((statement) => statement.length > 0)
      .map((statement) => `      ${JSON.stringify(statement)}`)
      .join(",\n")
    return `  {
    id: ${migration.id},
    name: ${JSON.stringify(migration.name)},
    statements: [
${statements}
    ]
  }`
  }).join(",\n")

  return `// GENERATED by \`bun run db:generate\`. Do not edit.
//
// One entry per file in db/migrations, in journal order, split on drizzle's
// statement breakpoints.

import type { Migration } from ${JSON.stringify(input.typeImport)}

export const ${input.exportName}: ReadonlyArray<Migration> = [
${entries}
]
`
}

const command = Command.make("embed-migrations", {
  packageDirectory: Flag.string("package"),
  output: Flag.string("out"),
  exportName: Flag.string("name"),
  typeImport: Flag.string("type-import")
}, (flags) =>
  Effect.gen(function*() {
    const packageRoot = path.resolve(flags.packageDirectory)
    const migrationsDirectory = path.join(packageRoot, "db", "migrations")
    const outputPath = path.join(packageRoot, flags.output)
    const journal = decodeJournal(readFileSync(path.join(migrationsDirectory, "meta", "_journal.json"), "utf8"))
    const migrations = [...journal.entries]
      .sort((left, right) => left.idx - right.idx)
      .map((entry) => ({ id: entry.idx, name: entry.tag }))
    writeFileSync(outputPath, render({
      migrationsDirectory,
      exportName: flags.exportName,
      typeImport: flags.typeImport,
      migrations
    }))
    yield* Effect.log(`embedded ${migrations.length} migration(s) into ${path.relative(packageRoot, outputPath)}`)
  }))

Command.runWith(command, { version: "0.2.0" })(process.argv.slice(2)).pipe(
  Effect.provide(BunServices.layer),
  Effect.runPromise
)
