// GENERATED by `bun run db:generate`. Do not edit.
//
// One entry per file in db/migrations, in journal order, split on drizzle's
// statement breakpoints. Applied by src/migrate.ts.

export interface GatewayMigration {
  /** Journal index. Stamped in `gateway_migration`, so it never shifts. */
  readonly id: number
  readonly name: string
  readonly statements: ReadonlyArray<string>
}

export const gatewayMigrations: ReadonlyArray<GatewayMigration> = [
  {
    id: 0,
    name: "0000_gateway_baseline",
    statements: [
      "CREATE TABLE `gateway_access_profile` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`is_default` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `gateway_access_profile_name_tenant` ON `gateway_access_profile` (`tenant_id`,`name`);",
      "CREATE UNIQUE INDEX `gateway_access_profile_default_tenant` ON `gateway_access_profile` (`tenant_id`) WHERE is_default = 1;",
      "CREATE TABLE `gateway_access_profile_tool` (\n\t`access_profile_id` text NOT NULL,\n\t`owner` text NOT NULL,\n\t`subject` text,\n\t`integration` text NOT NULL,\n\t`connection_name` text NOT NULL,\n\t`tool` text NOT NULL,\n\tPRIMARY KEY(`access_profile_id`, `owner`, `subject`, `integration`, `connection_name`, `tool`),\n\tFOREIGN KEY (`access_profile_id`) REFERENCES `gateway_access_profile`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `gateway_access_profile_tool_route` ON `gateway_access_profile_tool` (`access_profile_id`,`owner`,CASE WHEN subject IS NULL THEN '' ELSE subject END,`integration`,`connection_name`,`tool`);",
      "CREATE TABLE `gateway_api_key` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`hash` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`last_used_at` integer,\n\t`revoked_at` integer,\n\tFOREIGN KEY (`client_id`) REFERENCES `gateway_client`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `gateway_api_key_hash_unique` ON `gateway_api_key` (`hash`);",
      "CREATE TABLE `gateway_approval_policy` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`is_default` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `gateway_approval_policy_name_tenant` ON `gateway_approval_policy` (`tenant_id`,`name`);",
      "CREATE UNIQUE INDEX `gateway_approval_policy_default_tenant` ON `gateway_approval_policy` (`tenant_id`) WHERE is_default = 1;",
      "CREATE TABLE `gateway_approval_policy_tool` (\n\t`approval_policy_id` text NOT NULL,\n\t`owner` text NOT NULL,\n\t`subject` text,\n\t`integration` text NOT NULL,\n\t`connection_name` text NOT NULL,\n\t`tool` text NOT NULL,\n\t`decision` text NOT NULL,\n\tPRIMARY KEY(`approval_policy_id`, `owner`, `subject`, `integration`, `connection_name`, `tool`),\n\tFOREIGN KEY (`approval_policy_id`) REFERENCES `gateway_approval_policy`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `gateway_approval_policy_tool_route` ON `gateway_approval_policy_tool` (`approval_policy_id`,`owner`,CASE WHEN subject IS NULL THEN '' ELSE subject END,`integration`,`connection_name`,`tool`);",
      "CREATE TABLE `gateway_audit` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`client_id` text,\n\t`alias` text,\n\t`tool` text,\n\t`owner` text,\n\t`subject` text,\n\t`integration` text,\n\t`connection_name` text,\n\t`decision` text,\n\t`outcome` text NOT NULL,\n\t`message` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `gateway_audit_arguments` (\n\t`audit_id` text PRIMARY KEY NOT NULL,\n\t`arguments` text NOT NULL,\n\t`expires_at` integer NOT NULL,\n\tFOREIGN KEY (`audit_id`) REFERENCES `gateway_audit`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `gateway_client` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`access_profile_id` text NOT NULL,\n\t`approval_policy_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`capabilities` text NOT NULL,\n\t`approval_delivery` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`revoked_at` integer,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`access_profile_id`) REFERENCES `gateway_access_profile`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`approval_policy_id`) REFERENCES `gateway_approval_policy`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `gateway_client_name_tenant` ON `gateway_client` (`tenant_id`,`name`);",
      "CREATE TABLE `gateway_external_identity` (\n\t`provider` text NOT NULL,\n\t`provider_subject` text NOT NULL,\n\t`subject_id` text NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`email` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tPRIMARY KEY(`provider`, `provider_subject`),\n\tFOREIGN KEY (`subject_id`) REFERENCES `gateway_subject`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `gateway_identity_oauth_state` (\n\t`state_hash` text PRIMARY KEY NOT NULL,\n\t`provider` text NOT NULL,\n\t`handoff_hash` text,\n\t`return_path` text,\n\t`expires_at` integer NOT NULL\n);",
      "CREATE TABLE `gateway_login` (\n\t`subject_id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`email` text NOT NULL,\n\t`password_hash` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`subject_id`) REFERENCES `gateway_subject`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `gateway_login_email_unique` ON `gateway_login` (`email`);",
      "CREATE TABLE `gateway_login_handoff` (\n\t`request_hash` text PRIMARY KEY NOT NULL,\n\t`subject_id` text,\n\t`tenant_id` text,\n\t`email` text,\n\t`created_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`collected_at` integer,\n\tFOREIGN KEY (`subject_id`) REFERENCES `gateway_subject`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `gateway_pending_approval` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`client_id` text NOT NULL,\n\t`approval_policy_id` text NOT NULL,\n\t`access_profile_id` text NOT NULL,\n\t`alias` text NOT NULL,\n\t`tool` text NOT NULL,\n\t`arguments` text NOT NULL,\n\t`arguments_lookup` text,\n\t`status` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`decided_at` integer,\n\t`decided_by` text,\n\t`result` text,\n\t`error` text,\n\t`collected_at` integer,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`client_id`) REFERENCES `gateway_client`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`approval_policy_id`) REFERENCES `gateway_approval_policy`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`access_profile_id`) REFERENCES `gateway_access_profile`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `gateway_pending_approval_retry` ON `gateway_pending_approval` (`approval_policy_id`,`access_profile_id`,`tool`,`arguments_lookup`,`arguments`) WHERE collected_at IS NULL;",
      "CREATE TABLE `gateway_session` (\n\t`token_hash` text PRIMARY KEY NOT NULL,\n\t`subject_id` text NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL,\n\tFOREIGN KEY (`subject_id`) REFERENCES `gateway_subject`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `gateway_subject` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tenant_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `gateway_tenant` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` integer NOT NULL\n);",
      "CREATE UNIQUE INDEX `gateway_tenant_name_unique` ON `gateway_tenant` (`name`);",
      "CREATE TABLE `gateway_tool_snapshot` (\n\t`tenant_id` text NOT NULL,\n\t`integration` text NOT NULL,\n\t`connection_name` text NOT NULL,\n\t`tool` text NOT NULL,\n\t`input_schema` text,\n\t`output_schema` text,\n\t`synced_at` integer NOT NULL,\n\tPRIMARY KEY(`tenant_id`, `integration`, `connection_name`, `tool`),\n\tFOREIGN KEY (`tenant_id`) REFERENCES `gateway_tenant`(`id`) ON UPDATE no action ON DELETE cascade\n);"
    ]
  }
]
